# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            LPP
tagline:          'Linux PI Programmers'
description:      'Implementing the Proportional Integral (PI) AQM in the Linux Kernel'
url:              http://linux-pi-programmers.github.io
baseurl:          ''

author:
  name:           'Linux PI Programmers'
  url:            https://github.com/linux-pi-programmers/linux

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/linux-pi-programmers/linux
